# Copyright 2020 (c) Ayane Satomi
# Published under CC0-Universal.
#
#
# Keep in mind this configuration is domain-specific, some things may not work in your end.
apiVersion: v1
kind: ConfigMap
metadata:
  name: spigot-suzuhara-config
  annotations:
    mc.suzuhara.moe/deployment: minecraft
data:
  bukkit.yml: |
    settings:
       allow-end: true
       warn-on-overload: true
       permissions-file: permissions.yml
       update-folder: update
       plugin-profiling: false
       connection-throttle: 4000
       query-plugins: true
       deprecated-verbose: default
       shutdown-message: Whoopsie! Server is offline, try again later.
       world-container: /world/
    spawn-limits:
       monsters: 70
       animals: 15
       water-animals: 5
       ambient: 15
    chunk-gc:
       period-in-ticks: 600
       load-threshold: 0
    ticks-per:
       animal-spawns: 400
       monster-spawns: 1
       autosave: 6000
    aliases: now-in-commands.yml    
  server.properties: |
    generator-settings=
    use-native-transport=true
    op-permission-level=4
    allow-nether=true
    level-name=konlulu
    enable-query=false
    allow-flight=false
    prevent-proxy-connections=false
    server-port=25565
    max-world-size=29999984
    level-type=DEFAULT
    enable-rcon=false
    level-seed=konlulu
    force-gamemode=false
    server-ip=
    network-compression-threshold=256
    max-build-height=256
    spawn-npcs=true
    white-list=false
    spawn-animals=true
    hardcore=false
    snooper-enabled=true
    resource-pack-sha1=
    online-mode=true
    resource-pack=
    pvp=false
    difficulty=0
    enable-command-block=false
    gamemode=0
    player-idle-timeout=0
    max-players=20
    spawn-monsters=true
    generate-structures=true
    view-distance=10
    motd=Welcome to the Suzuhara Experimental Minecraft Server. Keep in mind QoS is not guranteed as this is an experiment. If you want to support us, consider being donator at ko-fi.com/capuccino