name: Docker Image Test Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file fabric.dockerfile --tag my-image-name:$(date +%s)
